2023-07-04 15:41:54,116 - DEBUG - STREAM b'IHDR' 16 13
2023-07-04 15:41:54,116 - DEBUG - STREAM b'sRGB' 41 1
2023-07-04 15:41:54,116 - DEBUG - STREAM b'gAMA' 54 4
2023-07-04 15:41:54,117 - DEBUG - STREAM b'IDAT' 70 65466
2023-07-04 15:41:54,190 - ERROR - Internal Server Error: /products/saveImage/
Traceback (most recent call last):
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\django\db\backends\mysql\base.py", line 75, in execute
    return self.cursor.execute(query, args)
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\MySQLdb\cursors.py", line 206, in execute
    res = self._query(query)
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\MySQLdb\cursors.py", line 319, in _query
    db.query(q)
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\MySQLdb\connections.py", line 254, in query
    _mysql.connection.query(self, query)
MySQLdb.OperationalError: (1054, "Unknown column 'image' in 'field list'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\rest_framework\mixins.py", line 19, in create
    self.perform_create(serializer)
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\rest_framework\mixins.py", line 24, in perform_create
    serializer.save()
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\rest_framework\serializers.py", line 212, in save
    self.instance = self.create(validated_data)
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\rest_framework\serializers.py", line 962, in create
    instance = ModelClass._default_manager.create(**validated_data)
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\django\db\models\query.py", line 658, in create
    obj.save(force_insert=True, using=self.db)
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\django\db\models\base.py", line 814, in save
    self.save_base(
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\django\db\models\base.py", line 877, in save_base
    updated = self._save_table(
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\django\db\models\base.py", line 1020, in _save_table
    results = self._do_insert(
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\django\db\models\base.py", line 1061, in _do_insert
    return manager._insert(
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\django\db\models\query.py", line 1805, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\django\db\models\sql\compiler.py", line 1822, in execute_sql
    cursor.execute(sql, params)
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\django\db\backends\utils.py", line 102, in execute
    return super().execute(sql, params)
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\django\db\backends\mysql\base.py", line 75, in execute
    return self.cursor.execute(query, args)
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\MySQLdb\cursors.py", line 206, in execute
    res = self._query(query)
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\MySQLdb\cursors.py", line 319, in _query
    db.query(q)
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\MySQLdb\connections.py", line 254, in query
    _mysql.connection.query(self, query)
django.db.utils.OperationalError: (1054, "Unknown column 'image' in 'field list'")
2023-07-04 15:42:44,688 - INFO - D:\E Nursery Project\e-nursery-django\e_nursery\Scripts\e_nursery\products_app\views.py changed, reloading.
2023-07-04 15:42:45,742 - INFO - Starts
2023-07-04 15:42:45,742 - INFO - Serialized
2023-07-04 15:43:04,567 - INFO - D:\E Nursery Project\e-nursery-django\e_nursery\Scripts\e_nursery\products_app\views.py changed, reloading.
2023-07-04 15:43:05,366 - INFO - Starts
2023-07-04 15:43:05,366 - INFO - Serialized
2023-07-04 15:43:09,029 - INFO - D:\E Nursery Project\e-nursery-django\e_nursery\Scripts\e_nursery\products_app\views.py changed, reloading.
2023-07-04 15:43:09,880 - INFO - Starts
2023-07-04 15:43:09,881 - INFO - Serialized
2023-07-04 15:43:15,742 - INFO - D:\E Nursery Project\e-nursery-django\e_nursery\Scripts\e_nursery\products_app\views.py changed, reloading.
2023-07-04 15:43:16,606 - INFO - Starts
2023-07-04 15:43:16,606 - INFO - Serialized
2023-07-04 15:43:18,704 - DEBUG - STREAM b'IHDR' 16 13
2023-07-04 15:43:18,704 - DEBUG - STREAM b'sRGB' 41 1
2023-07-04 15:43:18,704 - DEBUG - STREAM b'gAMA' 54 4
2023-07-04 15:43:18,704 - DEBUG - STREAM b'IDAT' 70 65466
2023-07-04 15:43:18,706 - DEBUG - Importing BlpImagePlugin
2023-07-04 15:43:18,708 - DEBUG - Importing BmpImagePlugin
2023-07-04 15:43:18,708 - DEBUG - Importing BufrStubImagePlugin
2023-07-04 15:43:18,709 - DEBUG - Importing CurImagePlugin
2023-07-04 15:43:18,709 - DEBUG - Importing DcxImagePlugin
2023-07-04 15:43:18,711 - DEBUG - Importing DdsImagePlugin
2023-07-04 15:43:18,712 - DEBUG - Importing EpsImagePlugin
2023-07-04 15:43:18,739 - DEBUG - Importing FitsImagePlugin
2023-07-04 15:43:18,739 - DEBUG - Importing FliImagePlugin
2023-07-04 15:43:18,741 - DEBUG - Importing FpxImagePlugin
2023-07-04 15:43:18,741 - DEBUG - Image: failed to import FpxImagePlugin: No module named 'olefile'
2023-07-04 15:43:18,741 - DEBUG - Importing FtexImagePlugin
2023-07-04 15:43:18,742 - DEBUG - Importing GbrImagePlugin
2023-07-04 15:43:18,743 - DEBUG - Importing GifImagePlugin
2023-07-04 15:43:18,743 - DEBUG - Importing GribStubImagePlugin
2023-07-04 15:43:18,745 - DEBUG - Importing Hdf5StubImagePlugin
2023-07-04 15:43:18,746 - DEBUG - Importing IcnsImagePlugin
2023-07-04 15:43:18,749 - DEBUG - Importing IcoImagePlugin
2023-07-04 15:43:18,750 - DEBUG - Importing ImImagePlugin
2023-07-04 15:43:18,751 - DEBUG - Importing ImtImagePlugin
2023-07-04 15:43:18,752 - DEBUG - Importing IptcImagePlugin
2023-07-04 15:43:18,754 - DEBUG - Importing JpegImagePlugin
2023-07-04 15:43:18,754 - DEBUG - Importing Jpeg2KImagePlugin
2023-07-04 15:43:18,754 - DEBUG - Importing McIdasImagePlugin
2023-07-04 15:43:18,754 - DEBUG - Importing MicImagePlugin
2023-07-04 15:43:18,755 - DEBUG - Image: failed to import MicImagePlugin: No module named 'olefile'
2023-07-04 15:43:18,755 - DEBUG - Importing MpegImagePlugin
2023-07-04 15:43:18,757 - DEBUG - Importing MpoImagePlugin
2023-07-04 15:43:18,765 - DEBUG - Importing MspImagePlugin
2023-07-04 15:43:18,766 - DEBUG - Importing PalmImagePlugin
2023-07-04 15:43:18,767 - DEBUG - Importing PcdImagePlugin
2023-07-04 15:43:18,768 - DEBUG - Importing PcxImagePlugin
2023-07-04 15:43:18,768 - DEBUG - Importing PdfImagePlugin
2023-07-04 15:43:18,774 - DEBUG - Importing PixarImagePlugin
2023-07-04 15:43:18,776 - DEBUG - Importing PngImagePlugin
2023-07-04 15:43:18,776 - DEBUG - Importing PpmImagePlugin
2023-07-04 15:43:18,776 - DEBUG - Importing PsdImagePlugin
2023-07-04 15:43:18,776 - DEBUG - Importing QoiImagePlugin
2023-07-04 15:43:18,777 - DEBUG - Importing SgiImagePlugin
2023-07-04 15:43:18,779 - DEBUG - Importing SpiderImagePlugin
2023-07-04 15:43:18,780 - DEBUG - Importing SunImagePlugin
2023-07-04 15:43:18,781 - DEBUG - Importing TgaImagePlugin
2023-07-04 15:43:18,782 - DEBUG - Importing TiffImagePlugin
2023-07-04 15:43:18,782 - DEBUG - Importing WebPImagePlugin
2023-07-04 15:43:18,783 - DEBUG - Importing WmfImagePlugin
2023-07-04 15:43:18,784 - DEBUG - Importing XbmImagePlugin
2023-07-04 15:43:18,786 - DEBUG - Importing XpmImagePlugin
2023-07-04 15:43:18,787 - DEBUG - Importing XVThumbImagePlugin
2023-07-04 15:43:18,967 - ERROR - Internal Server Error: /products/saveImage/
Traceback (most recent call last):
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\django\db\backends\mysql\base.py", line 75, in execute
    return self.cursor.execute(query, args)
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\MySQLdb\cursors.py", line 206, in execute
    res = self._query(query)
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\MySQLdb\cursors.py", line 319, in _query
    db.query(q)
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\MySQLdb\connections.py", line 254, in query
    _mysql.connection.query(self, query)
MySQLdb.OperationalError: (1054, "Unknown column 'image' in 'field list'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\rest_framework\mixins.py", line 19, in create
    self.perform_create(serializer)
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\rest_framework\mixins.py", line 24, in perform_create
    serializer.save()
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\rest_framework\serializers.py", line 212, in save
    self.instance = self.create(validated_data)
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\rest_framework\serializers.py", line 962, in create
    instance = ModelClass._default_manager.create(**validated_data)
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\django\db\models\query.py", line 658, in create
    obj.save(force_insert=True, using=self.db)
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\django\db\models\base.py", line 814, in save
    self.save_base(
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\django\db\models\base.py", line 877, in save_base
    updated = self._save_table(
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\django\db\models\base.py", line 1020, in _save_table
    results = self._do_insert(
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\django\db\models\base.py", line 1061, in _do_insert
    return manager._insert(
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\django\db\models\query.py", line 1805, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\django\db\models\sql\compiler.py", line 1822, in execute_sql
    cursor.execute(sql, params)
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\django\db\backends\utils.py", line 102, in execute
    return super().execute(sql, params)
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\django\db\backends\mysql\base.py", line 75, in execute
    return self.cursor.execute(query, args)
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\MySQLdb\cursors.py", line 206, in execute
    res = self._query(query)
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\MySQLdb\cursors.py", line 319, in _query
    db.query(q)
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\MySQLdb\connections.py", line 254, in query
    _mysql.connection.query(self, query)
django.db.utils.OperationalError: (1054, "Unknown column 'image' in 'field list'")
2023-07-04 15:44:03,825 - INFO - D:\E Nursery Project\e-nursery-django\e_nursery\Scripts\e_nursery\products_app\views.py changed, reloading.
2023-07-04 15:44:04,707 - INFO - Starts
2023-07-04 15:44:04,707 - INFO - Serialized
2023-07-04 15:44:06,036 - DEBUG - STREAM b'IHDR' 16 13
2023-07-04 15:44:06,036 - DEBUG - STREAM b'sRGB' 41 1
2023-07-04 15:44:06,036 - DEBUG - STREAM b'gAMA' 54 4
2023-07-04 15:44:06,036 - DEBUG - STREAM b'IDAT' 70 65466
2023-07-04 15:44:06,038 - DEBUG - Importing BlpImagePlugin
2023-07-04 15:44:06,040 - DEBUG - Importing BmpImagePlugin
2023-07-04 15:44:06,040 - DEBUG - Importing BufrStubImagePlugin
2023-07-04 15:44:06,041 - DEBUG - Importing CurImagePlugin
2023-07-04 15:44:06,042 - DEBUG - Importing DcxImagePlugin
2023-07-04 15:44:06,045 - DEBUG - Importing DdsImagePlugin
2023-07-04 15:44:06,046 - DEBUG - Importing EpsImagePlugin
2023-07-04 15:44:06,093 - DEBUG - Importing FitsImagePlugin
2023-07-04 15:44:06,093 - DEBUG - Importing FliImagePlugin
2023-07-04 15:44:06,094 - DEBUG - Importing FpxImagePlugin
2023-07-04 15:44:06,096 - DEBUG - Image: failed to import FpxImagePlugin: No module named 'olefile'
2023-07-04 15:44:06,096 - DEBUG - Importing FtexImagePlugin
2023-07-04 15:44:06,097 - DEBUG - Importing GbrImagePlugin
2023-07-04 15:44:06,098 - DEBUG - Importing GifImagePlugin
2023-07-04 15:44:06,098 - DEBUG - Importing GribStubImagePlugin
2023-07-04 15:44:06,099 - DEBUG - Importing Hdf5StubImagePlugin
2023-07-04 15:44:06,101 - DEBUG - Importing IcnsImagePlugin
2023-07-04 15:44:06,103 - DEBUG - Importing IcoImagePlugin
2023-07-04 15:44:06,104 - DEBUG - Importing ImImagePlugin
2023-07-04 15:44:06,105 - DEBUG - Importing ImtImagePlugin
2023-07-04 15:44:06,106 - DEBUG - Importing IptcImagePlugin
2023-07-04 15:44:06,107 - DEBUG - Importing JpegImagePlugin
2023-07-04 15:44:06,107 - DEBUG - Importing Jpeg2KImagePlugin
2023-07-04 15:44:06,107 - DEBUG - Importing McIdasImagePlugin
2023-07-04 15:44:06,108 - DEBUG - Importing MicImagePlugin
2023-07-04 15:44:06,109 - DEBUG - Image: failed to import MicImagePlugin: No module named 'olefile'
2023-07-04 15:44:06,109 - DEBUG - Importing MpegImagePlugin
2023-07-04 15:44:06,110 - DEBUG - Importing MpoImagePlugin
2023-07-04 15:44:06,115 - DEBUG - Importing MspImagePlugin
2023-07-04 15:44:06,116 - DEBUG - Importing PalmImagePlugin
2023-07-04 15:44:06,117 - DEBUG - Importing PcdImagePlugin
2023-07-04 15:44:06,118 - DEBUG - Importing PcxImagePlugin
2023-07-04 15:44:06,118 - DEBUG - Importing PdfImagePlugin
2023-07-04 15:44:06,125 - DEBUG - Importing PixarImagePlugin
2023-07-04 15:44:06,126 - DEBUG - Importing PngImagePlugin
2023-07-04 15:44:06,126 - DEBUG - Importing PpmImagePlugin
2023-07-04 15:44:06,126 - DEBUG - Importing PsdImagePlugin
2023-07-04 15:44:06,127 - DEBUG - Importing QoiImagePlugin
2023-07-04 15:44:06,127 - DEBUG - Importing SgiImagePlugin
2023-07-04 15:44:06,128 - DEBUG - Importing SpiderImagePlugin
2023-07-04 15:44:06,129 - DEBUG - Importing SunImagePlugin
2023-07-04 15:44:06,131 - DEBUG - Importing TgaImagePlugin
2023-07-04 15:44:06,133 - DEBUG - Importing TiffImagePlugin
2023-07-04 15:44:06,133 - DEBUG - Importing WebPImagePlugin
2023-07-04 15:44:06,135 - DEBUG - Importing WmfImagePlugin
2023-07-04 15:44:06,136 - DEBUG - Importing XbmImagePlugin
2023-07-04 15:44:06,137 - DEBUG - Importing XpmImagePlugin
2023-07-04 15:44:06,138 - DEBUG - Importing XVThumbImagePlugin
2023-07-04 15:44:06,229 - ERROR - Internal Server Error: /products/saveImage/
Traceback (most recent call last):
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\django\db\backends\mysql\base.py", line 75, in execute
    return self.cursor.execute(query, args)
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\MySQLdb\cursors.py", line 206, in execute
    res = self._query(query)
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\MySQLdb\cursors.py", line 319, in _query
    db.query(q)
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\MySQLdb\connections.py", line 254, in query
    _mysql.connection.query(self, query)
MySQLdb.OperationalError: (1054, "Unknown column 'image' in 'field list'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\rest_framework\mixins.py", line 19, in create
    self.perform_create(serializer)
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\rest_framework\mixins.py", line 24, in perform_create
    serializer.save()
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\rest_framework\serializers.py", line 212, in save
    self.instance = self.create(validated_data)
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\rest_framework\serializers.py", line 962, in create
    instance = ModelClass._default_manager.create(**validated_data)
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\django\db\models\query.py", line 658, in create
    obj.save(force_insert=True, using=self.db)
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\django\db\models\base.py", line 814, in save
    self.save_base(
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\django\db\models\base.py", line 877, in save_base
    updated = self._save_table(
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\django\db\models\base.py", line 1020, in _save_table
    results = self._do_insert(
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\django\db\models\base.py", line 1061, in _do_insert
    return manager._insert(
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\django\db\models\query.py", line 1805, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\django\db\models\sql\compiler.py", line 1822, in execute_sql
    cursor.execute(sql, params)
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\django\db\backends\utils.py", line 102, in execute
    return super().execute(sql, params)
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\django\db\backends\mysql\base.py", line 75, in execute
    return self.cursor.execute(query, args)
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\MySQLdb\cursors.py", line 206, in execute
    res = self._query(query)
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\MySQLdb\cursors.py", line 319, in _query
    db.query(q)
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\MySQLdb\connections.py", line 254, in query
    _mysql.connection.query(self, query)
django.db.utils.OperationalError: (1054, "Unknown column 'image' in 'field list'")
2023-07-04 15:45:58,436 - INFO - D:\E Nursery Project\e-nursery-django\e_nursery\Scripts\e_nursery\products_app\views.py changed, reloading.
2023-07-04 15:45:59,297 - INFO - Starts
2023-07-04 15:45:59,298 - INFO - Serialized
2023-07-04 15:46:06,852 - DEBUG - STREAM b'IHDR' 16 13
2023-07-04 15:46:06,852 - DEBUG - STREAM b'sRGB' 41 1
2023-07-04 15:46:06,852 - DEBUG - STREAM b'gAMA' 54 4
2023-07-04 15:46:06,853 - DEBUG - STREAM b'IDAT' 70 65466
2023-07-04 15:46:06,856 - DEBUG - Importing BlpImagePlugin
2023-07-04 15:46:06,858 - DEBUG - Importing BmpImagePlugin
2023-07-04 15:46:06,859 - DEBUG - Importing BufrStubImagePlugin
2023-07-04 15:46:06,860 - DEBUG - Importing CurImagePlugin
2023-07-04 15:46:06,862 - DEBUG - Importing DcxImagePlugin
2023-07-04 15:46:06,867 - DEBUG - Importing DdsImagePlugin
2023-07-04 15:46:06,870 - DEBUG - Importing EpsImagePlugin
2023-07-04 15:46:06,926 - DEBUG - Importing FitsImagePlugin
2023-07-04 15:46:06,928 - DEBUG - Importing FliImagePlugin
2023-07-04 15:46:06,929 - DEBUG - Importing FpxImagePlugin
2023-07-04 15:46:06,933 - DEBUG - Image: failed to import FpxImagePlugin: No module named 'olefile'
2023-07-04 15:46:06,933 - DEBUG - Importing FtexImagePlugin
2023-07-04 15:46:06,935 - DEBUG - Importing GbrImagePlugin
2023-07-04 15:46:06,936 - DEBUG - Importing GifImagePlugin
2023-07-04 15:46:06,936 - DEBUG - Importing GribStubImagePlugin
2023-07-04 15:46:06,937 - DEBUG - Importing Hdf5StubImagePlugin
2023-07-04 15:46:06,938 - DEBUG - Importing IcnsImagePlugin
2023-07-04 15:46:06,941 - DEBUG - Importing IcoImagePlugin
2023-07-04 15:46:06,943 - DEBUG - Importing ImImagePlugin
2023-07-04 15:46:06,944 - DEBUG - Importing ImtImagePlugin
2023-07-04 15:46:06,945 - DEBUG - Importing IptcImagePlugin
2023-07-04 15:46:06,946 - DEBUG - Importing JpegImagePlugin
2023-07-04 15:46:06,946 - DEBUG - Importing Jpeg2KImagePlugin
2023-07-04 15:46:06,946 - DEBUG - Importing McIdasImagePlugin
2023-07-04 15:46:06,947 - DEBUG - Importing MicImagePlugin
2023-07-04 15:46:06,949 - DEBUG - Image: failed to import MicImagePlugin: No module named 'olefile'
2023-07-04 15:46:06,949 - DEBUG - Importing MpegImagePlugin
2023-07-04 15:46:06,950 - DEBUG - Importing MpoImagePlugin
2023-07-04 15:46:06,956 - DEBUG - Importing MspImagePlugin
2023-07-04 15:46:06,957 - DEBUG - Importing PalmImagePlugin
2023-07-04 15:46:06,958 - DEBUG - Importing PcdImagePlugin
2023-07-04 15:46:06,959 - DEBUG - Importing PcxImagePlugin
2023-07-04 15:46:06,959 - DEBUG - Importing PdfImagePlugin
2023-07-04 15:46:06,968 - DEBUG - Importing PixarImagePlugin
2023-07-04 15:46:06,969 - DEBUG - Importing PngImagePlugin
2023-07-04 15:46:06,969 - DEBUG - Importing PpmImagePlugin
2023-07-04 15:46:06,969 - DEBUG - Importing PsdImagePlugin
2023-07-04 15:46:06,970 - DEBUG - Importing QoiImagePlugin
2023-07-04 15:46:06,971 - DEBUG - Importing SgiImagePlugin
2023-07-04 15:46:06,972 - DEBUG - Importing SpiderImagePlugin
2023-07-04 15:46:06,973 - DEBUG - Importing SunImagePlugin
2023-07-04 15:46:06,974 - DEBUG - Importing TgaImagePlugin
2023-07-04 15:46:06,975 - DEBUG - Importing TiffImagePlugin
2023-07-04 15:46:06,975 - DEBUG - Importing WebPImagePlugin
2023-07-04 15:46:06,976 - DEBUG - Importing WmfImagePlugin
2023-07-04 15:46:06,978 - DEBUG - Importing XbmImagePlugin
2023-07-04 15:46:06,980 - DEBUG - Importing XpmImagePlugin
2023-07-04 15:46:06,981 - DEBUG - Importing XVThumbImagePlugin
2023-07-04 15:46:07,070 - ERROR - Internal Server Error: /products/saveImage/
Traceback (most recent call last):
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\django\db\backends\mysql\base.py", line 75, in execute
    return self.cursor.execute(query, args)
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\MySQLdb\cursors.py", line 206, in execute
    res = self._query(query)
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\MySQLdb\cursors.py", line 319, in _query
    db.query(q)
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\MySQLdb\connections.py", line 254, in query
    _mysql.connection.query(self, query)
MySQLdb.OperationalError: (1054, "Unknown column 'image' in 'field list'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\rest_framework\mixins.py", line 19, in create
    self.perform_create(serializer)
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\rest_framework\mixins.py", line 24, in perform_create
    serializer.save()
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\rest_framework\serializers.py", line 212, in save
    self.instance = self.create(validated_data)
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\rest_framework\serializers.py", line 962, in create
    instance = ModelClass._default_manager.create(**validated_data)
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\django\db\models\query.py", line 658, in create
    obj.save(force_insert=True, using=self.db)
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\django\db\models\base.py", line 814, in save
    self.save_base(
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\django\db\models\base.py", line 877, in save_base
    updated = self._save_table(
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\django\db\models\base.py", line 1020, in _save_table
    results = self._do_insert(
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\django\db\models\base.py", line 1061, in _do_insert
    return manager._insert(
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\django\db\models\query.py", line 1805, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\django\db\models\sql\compiler.py", line 1822, in execute_sql
    cursor.execute(sql, params)
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\django\db\backends\utils.py", line 102, in execute
    return super().execute(sql, params)
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\django\db\backends\mysql\base.py", line 75, in execute
    return self.cursor.execute(query, args)
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\MySQLdb\cursors.py", line 206, in execute
    res = self._query(query)
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\MySQLdb\cursors.py", line 319, in _query
    db.query(q)
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\MySQLdb\connections.py", line 254, in query
    _mysql.connection.query(self, query)
django.db.utils.OperationalError: (1054, "Unknown column 'image' in 'field list'")
2023-07-04 15:47:52,815 - INFO - Starts
2023-07-04 15:47:52,815 - INFO - Serialized
2023-07-04 15:47:55,833 - INFO - Starts
2023-07-04 15:47:55,833 - INFO - Serialized
2023-07-04 15:47:58,323 - INFO - Starts
2023-07-04 15:47:58,323 - INFO - Serialized
2023-07-04 15:48:06,053 - DEBUG - STREAM b'IHDR' 16 13
2023-07-04 15:48:06,053 - DEBUG - STREAM b'sRGB' 41 1
2023-07-04 15:48:06,053 - DEBUG - STREAM b'gAMA' 54 4
2023-07-04 15:48:06,053 - DEBUG - STREAM b'IDAT' 70 65466
2023-07-04 15:48:06,056 - DEBUG - Importing BlpImagePlugin
2023-07-04 15:48:06,058 - DEBUG - Importing BmpImagePlugin
2023-07-04 15:48:06,058 - DEBUG - Importing BufrStubImagePlugin
2023-07-04 15:48:06,059 - DEBUG - Importing CurImagePlugin
2023-07-04 15:48:06,060 - DEBUG - Importing DcxImagePlugin
2023-07-04 15:48:06,062 - DEBUG - Importing DdsImagePlugin
2023-07-04 15:48:06,065 - DEBUG - Importing EpsImagePlugin
2023-07-04 15:48:06,099 - DEBUG - Importing FitsImagePlugin
2023-07-04 15:48:06,100 - DEBUG - Importing FliImagePlugin
2023-07-04 15:48:06,101 - DEBUG - Importing FpxImagePlugin
2023-07-04 15:48:06,102 - DEBUG - Image: failed to import FpxImagePlugin: No module named 'olefile'
2023-07-04 15:48:06,102 - DEBUG - Importing FtexImagePlugin
2023-07-04 15:48:06,103 - DEBUG - Importing GbrImagePlugin
2023-07-04 15:48:06,104 - DEBUG - Importing GifImagePlugin
2023-07-04 15:48:06,104 - DEBUG - Importing GribStubImagePlugin
2023-07-04 15:48:06,104 - DEBUG - Importing Hdf5StubImagePlugin
2023-07-04 15:48:06,105 - DEBUG - Importing IcnsImagePlugin
2023-07-04 15:48:06,107 - DEBUG - Importing IcoImagePlugin
2023-07-04 15:48:06,108 - DEBUG - Importing ImImagePlugin
2023-07-04 15:48:06,109 - DEBUG - Importing ImtImagePlugin
2023-07-04 15:48:06,110 - DEBUG - Importing IptcImagePlugin
2023-07-04 15:48:06,111 - DEBUG - Importing JpegImagePlugin
2023-07-04 15:48:06,111 - DEBUG - Importing Jpeg2KImagePlugin
2023-07-04 15:48:06,111 - DEBUG - Importing McIdasImagePlugin
2023-07-04 15:48:06,111 - DEBUG - Importing MicImagePlugin
2023-07-04 15:48:06,113 - DEBUG - Image: failed to import MicImagePlugin: No module named 'olefile'
2023-07-04 15:48:06,113 - DEBUG - Importing MpegImagePlugin
2023-07-04 15:48:06,115 - DEBUG - Importing MpoImagePlugin
2023-07-04 15:48:06,120 - DEBUG - Importing MspImagePlugin
2023-07-04 15:48:06,121 - DEBUG - Importing PalmImagePlugin
2023-07-04 15:48:06,122 - DEBUG - Importing PcdImagePlugin
2023-07-04 15:48:06,123 - DEBUG - Importing PcxImagePlugin
2023-07-04 15:48:06,123 - DEBUG - Importing PdfImagePlugin
2023-07-04 15:48:06,129 - DEBUG - Importing PixarImagePlugin
2023-07-04 15:48:06,131 - DEBUG - Importing PngImagePlugin
2023-07-04 15:48:06,131 - DEBUG - Importing PpmImagePlugin
2023-07-04 15:48:06,131 - DEBUG - Importing PsdImagePlugin
2023-07-04 15:48:06,132 - DEBUG - Importing QoiImagePlugin
2023-07-04 15:48:06,133 - DEBUG - Importing SgiImagePlugin
2023-07-04 15:48:06,134 - DEBUG - Importing SpiderImagePlugin
2023-07-04 15:48:06,134 - DEBUG - Importing SunImagePlugin
2023-07-04 15:48:06,135 - DEBUG - Importing TgaImagePlugin
2023-07-04 15:48:06,136 - DEBUG - Importing TiffImagePlugin
2023-07-04 15:48:06,136 - DEBUG - Importing WebPImagePlugin
2023-07-04 15:48:06,137 - DEBUG - Importing WmfImagePlugin
2023-07-04 15:48:06,138 - DEBUG - Importing XbmImagePlugin
2023-07-04 15:48:06,140 - DEBUG - Importing XpmImagePlugin
2023-07-04 15:48:06,141 - DEBUG - Importing XVThumbImagePlugin
2023-07-04 17:07:41,544 - DEBUG - STREAM b'IHDR' 16 13
2023-07-04 17:07:41,544 - DEBUG - STREAM b'sRGB' 41 1
2023-07-04 17:07:41,544 - DEBUG - STREAM b'gAMA' 54 4
2023-07-04 17:07:41,544 - DEBUG - STREAM b'IDAT' 70 65466
2023-07-04 17:11:16,418 - INFO - login_customer function started
2023-07-04 17:11:16,426 - INFO - Email exists**********************************************
2023-07-04 17:11:16,426 - ERROR - U2FtdW5kYXJAMTIz
2023-07-04 17:11:16,426 - ERROR - pbkdf2_sha256$600000$HSfD1P9hMHfoEEpxPrWtIU$wYJzNwv0mDb1oEasqrA48tuu73OguGVb+zXEiJVqD2k=
2023-07-04 17:11:16,859 - INFO - Password is correct
2023-07-04 17:12:10,409 - INFO - login_customer function started
2023-07-04 17:12:10,415 - INFO - Email exists**********************************************
2023-07-04 17:12:10,416 - ERROR - QW5rdXNoQDEyMw==
2023-07-04 17:12:10,416 - ERROR - pbkdf2_sha256$600000$GEdF8EPljGKrGKY8koTM2S$cDrVhtUP/TAQukXjVnSRo5xfVccz7KOnLyGz6Hm1UqE=
2023-07-04 17:12:10,851 - INFO - Password is correct
2023-07-04 17:12:14,744 - INFO - GET method
2023-07-04 17:12:14,744 - INFO - getting all images
2023-07-04 17:12:14,844 - ERROR - Internal Server Error: /products/products/
Traceback (most recent call last):
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\django\db\backends\mysql\base.py", line 75, in execute
    return self.cursor.execute(query, args)
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\MySQLdb\cursors.py", line 206, in execute
    res = self._query(query)
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\MySQLdb\cursors.py", line 319, in _query
    db.query(q)
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\MySQLdb\connections.py", line 254, in query
    _mysql.connection.query(self, query)
MySQLdb.OperationalError: (1054, "Unknown column 'product.image_id_id' in 'field list'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "D:\E Nursery Project\e-nursery-django\e_nursery\Scripts\e_nursery\products_app\views.py", line 137, in getAllProducts
    return JsonResponse(products_serializer.data,safe=False)
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\rest_framework\serializers.py", line 768, in data
    ret = super().data
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\rest_framework\serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\rest_framework\serializers.py", line 686, in to_representation
    return [
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\django\db\models\query.py", line 398, in __iter__
    self._fetch_all()
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\django\db\models\query.py", line 1881, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\django\db\models\sql\compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\django\db\backends\utils.py", line 102, in execute
    return super().execute(sql, params)
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\django\db\backends\mysql\base.py", line 75, in execute
    return self.cursor.execute(query, args)
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\MySQLdb\cursors.py", line 206, in execute
    res = self._query(query)
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\MySQLdb\cursors.py", line 319, in _query
    db.query(q)
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\MySQLdb\connections.py", line 254, in query
    _mysql.connection.query(self, query)
django.db.utils.OperationalError: (1054, "Unknown column 'product.image_id_id' in 'field list'")
2023-07-04 17:12:53,529 - DEBUG - STREAM b'IHDR' 16 13
2023-07-04 17:12:53,530 - DEBUG - STREAM b'sRGB' 41 1
2023-07-04 17:12:53,530 - DEBUG - STREAM b'gAMA' 54 4
2023-07-04 17:12:53,530 - DEBUG - STREAM b'IDAT' 70 65466
2023-07-04 17:15:40,253 - INFO - GET method
2023-07-04 17:15:40,254 - INFO - getting all images
2023-07-04 17:15:40,409 - ERROR - Internal Server Error: /products/products/
Traceback (most recent call last):
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\django\db\backends\mysql\base.py", line 75, in execute
    return self.cursor.execute(query, args)
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\MySQLdb\cursors.py", line 206, in execute
    res = self._query(query)
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\MySQLdb\cursors.py", line 319, in _query
    db.query(q)
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\MySQLdb\connections.py", line 254, in query
    _mysql.connection.query(self, query)
MySQLdb.OperationalError: (1054, "Unknown column 'product.image_id_id' in 'field list'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "D:\E Nursery Project\e-nursery-django\e_nursery\Scripts\e_nursery\products_app\views.py", line 137, in getAllProducts
    return JsonResponse(products_serializer.data,safe=False)
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\rest_framework\serializers.py", line 768, in data
    ret = super().data
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\rest_framework\serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\rest_framework\serializers.py", line 686, in to_representation
    return [
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\django\db\models\query.py", line 398, in __iter__
    self._fetch_all()
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\django\db\models\query.py", line 1881, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\django\db\models\sql\compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\django\db\backends\utils.py", line 102, in execute
    return super().execute(sql, params)
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\django\db\backends\mysql\base.py", line 75, in execute
    return self.cursor.execute(query, args)
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\MySQLdb\cursors.py", line 206, in execute
    res = self._query(query)
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\MySQLdb\cursors.py", line 319, in _query
    db.query(q)
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\MySQLdb\connections.py", line 254, in query
    _mysql.connection.query(self, query)
django.db.utils.OperationalError: (1054, "Unknown column 'product.image_id_id' in 'field list'")
2023-07-04 17:15:41,307 - INFO - GET method
2023-07-04 17:15:41,308 - INFO - getting all images
2023-07-04 17:15:41,491 - ERROR - Internal Server Error: /products/products/
Traceback (most recent call last):
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\django\db\backends\mysql\base.py", line 75, in execute
    return self.cursor.execute(query, args)
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\MySQLdb\cursors.py", line 206, in execute
    res = self._query(query)
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\MySQLdb\cursors.py", line 319, in _query
    db.query(q)
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\MySQLdb\connections.py", line 254, in query
    _mysql.connection.query(self, query)
MySQLdb.OperationalError: (1054, "Unknown column 'product.image_id_id' in 'field list'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "D:\E Nursery Project\e-nursery-django\e_nursery\Scripts\e_nursery\products_app\views.py", line 137, in getAllProducts
    return JsonResponse(products_serializer.data,safe=False)
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\rest_framework\serializers.py", line 768, in data
    ret = super().data
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\rest_framework\serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\rest_framework\serializers.py", line 686, in to_representation
    return [
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\django\db\models\query.py", line 398, in __iter__
    self._fetch_all()
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\django\db\models\query.py", line 1881, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\django\db\models\sql\compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\django\db\backends\utils.py", line 102, in execute
    return super().execute(sql, params)
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\django\db\backends\mysql\base.py", line 75, in execute
    return self.cursor.execute(query, args)
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\MySQLdb\cursors.py", line 206, in execute
    res = self._query(query)
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\MySQLdb\cursors.py", line 319, in _query
    db.query(q)
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\MySQLdb\connections.py", line 254, in query
    _mysql.connection.query(self, query)
django.db.utils.OperationalError: (1054, "Unknown column 'product.image_id_id' in 'field list'")
2023-07-04 17:15:45,459 - INFO - GET method
2023-07-04 17:15:45,460 - INFO - getting all images
2023-07-04 17:15:45,617 - ERROR - Internal Server Error: /products/products/
Traceback (most recent call last):
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\django\db\backends\mysql\base.py", line 75, in execute
    return self.cursor.execute(query, args)
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\MySQLdb\cursors.py", line 206, in execute
    res = self._query(query)
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\MySQLdb\cursors.py", line 319, in _query
    db.query(q)
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\MySQLdb\connections.py", line 254, in query
    _mysql.connection.query(self, query)
MySQLdb.OperationalError: (1054, "Unknown column 'product.image_id_id' in 'field list'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "D:\E Nursery Project\e-nursery-django\e_nursery\Scripts\e_nursery\products_app\views.py", line 137, in getAllProducts
    return JsonResponse(products_serializer.data,safe=False)
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\rest_framework\serializers.py", line 768, in data
    ret = super().data
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\rest_framework\serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\rest_framework\serializers.py", line 686, in to_representation
    return [
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\django\db\models\query.py", line 398, in __iter__
    self._fetch_all()
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\django\db\models\query.py", line 1881, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\django\db\models\sql\compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\django\db\backends\utils.py", line 102, in execute
    return super().execute(sql, params)
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\django\db\backends\mysql\base.py", line 75, in execute
    return self.cursor.execute(query, args)
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\MySQLdb\cursors.py", line 206, in execute
    res = self._query(query)
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\MySQLdb\cursors.py", line 319, in _query
    db.query(q)
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\MySQLdb\connections.py", line 254, in query
    _mysql.connection.query(self, query)
django.db.utils.OperationalError: (1054, "Unknown column 'product.image_id_id' in 'field list'")
2023-07-04 17:15:46,444 - INFO - GET method
2023-07-04 17:15:46,444 - INFO - getting all images
2023-07-04 17:15:46,603 - ERROR - Internal Server Error: /products/products/
Traceback (most recent call last):
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\django\db\backends\mysql\base.py", line 75, in execute
    return self.cursor.execute(query, args)
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\MySQLdb\cursors.py", line 206, in execute
    res = self._query(query)
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\MySQLdb\cursors.py", line 319, in _query
    db.query(q)
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\MySQLdb\connections.py", line 254, in query
    _mysql.connection.query(self, query)
MySQLdb.OperationalError: (1054, "Unknown column 'product.image_id_id' in 'field list'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "D:\E Nursery Project\e-nursery-django\e_nursery\Scripts\e_nursery\products_app\views.py", line 137, in getAllProducts
    return JsonResponse(products_serializer.data,safe=False)
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\rest_framework\serializers.py", line 768, in data
    ret = super().data
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\rest_framework\serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\rest_framework\serializers.py", line 686, in to_representation
    return [
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\django\db\models\query.py", line 398, in __iter__
    self._fetch_all()
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\django\db\models\query.py", line 1881, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\django\db\models\sql\compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\django\db\backends\utils.py", line 102, in execute
    return super().execute(sql, params)
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\django\db\backends\mysql\base.py", line 75, in execute
    return self.cursor.execute(query, args)
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\MySQLdb\cursors.py", line 206, in execute
    res = self._query(query)
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\MySQLdb\cursors.py", line 319, in _query
    db.query(q)
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\MySQLdb\connections.py", line 254, in query
    _mysql.connection.query(self, query)
django.db.utils.OperationalError: (1054, "Unknown column 'product.image_id_id' in 'field list'")
2023-07-04 17:16:02,050 - INFO - GET method
2023-07-04 17:16:02,056 - INFO - getting all images
2023-07-04 17:16:02,200 - ERROR - Internal Server Error: /products/products/
Traceback (most recent call last):
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\django\db\backends\mysql\base.py", line 75, in execute
    return self.cursor.execute(query, args)
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\MySQLdb\cursors.py", line 206, in execute
    res = self._query(query)
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\MySQLdb\cursors.py", line 319, in _query
    db.query(q)
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\MySQLdb\connections.py", line 254, in query
    _mysql.connection.query(self, query)
MySQLdb.OperationalError: (1054, "Unknown column 'product.image_id_id' in 'field list'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "D:\E Nursery Project\e-nursery-django\e_nursery\Scripts\e_nursery\products_app\views.py", line 137, in getAllProducts
    return JsonResponse(products_serializer.data,safe=False)
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\rest_framework\serializers.py", line 768, in data
    ret = super().data
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\rest_framework\serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\rest_framework\serializers.py", line 686, in to_representation
    return [
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\django\db\models\query.py", line 398, in __iter__
    self._fetch_all()
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\django\db\models\query.py", line 1881, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\django\db\models\sql\compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\django\db\backends\utils.py", line 102, in execute
    return super().execute(sql, params)
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\django\db\backends\mysql\base.py", line 75, in execute
    return self.cursor.execute(query, args)
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\MySQLdb\cursors.py", line 206, in execute
    res = self._query(query)
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\MySQLdb\cursors.py", line 319, in _query
    db.query(q)
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\MySQLdb\connections.py", line 254, in query
    _mysql.connection.query(self, query)
django.db.utils.OperationalError: (1054, "Unknown column 'product.image_id_id' in 'field list'")
2023-07-04 17:16:03,168 - INFO - GET method
2023-07-04 17:16:03,168 - INFO - getting all images
2023-07-04 17:16:03,308 - ERROR - Internal Server Error: /products/products/
Traceback (most recent call last):
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\django\db\backends\mysql\base.py", line 75, in execute
    return self.cursor.execute(query, args)
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\MySQLdb\cursors.py", line 206, in execute
    res = self._query(query)
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\MySQLdb\cursors.py", line 319, in _query
    db.query(q)
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\MySQLdb\connections.py", line 254, in query
    _mysql.connection.query(self, query)
MySQLdb.OperationalError: (1054, "Unknown column 'product.image_id_id' in 'field list'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "D:\E Nursery Project\e-nursery-django\e_nursery\Scripts\e_nursery\products_app\views.py", line 137, in getAllProducts
    return JsonResponse(products_serializer.data,safe=False)
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\rest_framework\serializers.py", line 768, in data
    ret = super().data
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\rest_framework\serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\rest_framework\serializers.py", line 686, in to_representation
    return [
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\django\db\models\query.py", line 398, in __iter__
    self._fetch_all()
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\django\db\models\query.py", line 1881, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\django\db\models\sql\compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\django\db\backends\utils.py", line 102, in execute
    return super().execute(sql, params)
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\django\db\backends\mysql\base.py", line 75, in execute
    return self.cursor.execute(query, args)
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\MySQLdb\cursors.py", line 206, in execute
    res = self._query(query)
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\MySQLdb\cursors.py", line 319, in _query
    db.query(q)
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\MySQLdb\connections.py", line 254, in query
    _mysql.connection.query(self, query)
django.db.utils.OperationalError: (1054, "Unknown column 'product.image_id_id' in 'field list'")
2023-07-04 17:25:07,102 - INFO - GET method
2023-07-04 17:25:07,103 - INFO - getting all images
2023-07-04 17:25:07,280 - ERROR - Internal Server Error: /products/products/
Traceback (most recent call last):
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\django\db\backends\mysql\base.py", line 75, in execute
    return self.cursor.execute(query, args)
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\MySQLdb\cursors.py", line 206, in execute
    res = self._query(query)
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\MySQLdb\cursors.py", line 319, in _query
    db.query(q)
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\MySQLdb\connections.py", line 254, in query
    _mysql.connection.query(self, query)
MySQLdb.OperationalError: (1054, "Unknown column 'product.image_id_id' in 'field list'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "D:\E Nursery Project\e-nursery-django\e_nursery\Scripts\e_nursery\products_app\views.py", line 137, in getAllProducts
    return JsonResponse(products_serializer.data,safe=False)
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\rest_framework\serializers.py", line 768, in data
    ret = super().data
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\rest_framework\serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\rest_framework\serializers.py", line 686, in to_representation
    return [
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\django\db\models\query.py", line 398, in __iter__
    self._fetch_all()
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\django\db\models\query.py", line 1881, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\django\db\models\sql\compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\django\db\backends\utils.py", line 102, in execute
    return super().execute(sql, params)
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\django\db\backends\mysql\base.py", line 75, in execute
    return self.cursor.execute(query, args)
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\MySQLdb\cursors.py", line 206, in execute
    res = self._query(query)
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\MySQLdb\cursors.py", line 319, in _query
    db.query(q)
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\MySQLdb\connections.py", line 254, in query
    _mysql.connection.query(self, query)
django.db.utils.OperationalError: (1054, "Unknown column 'product.image_id_id' in 'field list'")
2023-07-04 17:25:07,448 - INFO - GET method
2023-07-04 17:25:07,449 - INFO - getting all images
2023-07-04 17:25:07,627 - ERROR - Internal Server Error: /products/products/
Traceback (most recent call last):
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\django\db\backends\mysql\base.py", line 75, in execute
    return self.cursor.execute(query, args)
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\MySQLdb\cursors.py", line 206, in execute
    res = self._query(query)
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\MySQLdb\cursors.py", line 319, in _query
    db.query(q)
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\MySQLdb\connections.py", line 254, in query
    _mysql.connection.query(self, query)
MySQLdb.OperationalError: (1054, "Unknown column 'product.image_id_id' in 'field list'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "D:\E Nursery Project\e-nursery-django\e_nursery\Scripts\e_nursery\products_app\views.py", line 137, in getAllProducts
    return JsonResponse(products_serializer.data,safe=False)
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\rest_framework\serializers.py", line 768, in data
    ret = super().data
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\rest_framework\serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\rest_framework\serializers.py", line 686, in to_representation
    return [
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\django\db\models\query.py", line 398, in __iter__
    self._fetch_all()
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\django\db\models\query.py", line 1881, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\django\db\models\sql\compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\django\db\backends\utils.py", line 102, in execute
    return super().execute(sql, params)
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\django\db\backends\mysql\base.py", line 75, in execute
    return self.cursor.execute(query, args)
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\MySQLdb\cursors.py", line 206, in execute
    res = self._query(query)
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\MySQLdb\cursors.py", line 319, in _query
    db.query(q)
  File "D:\E Nursery Project\e-nursery-django\e_nursery\lib\site-packages\MySQLdb\connections.py", line 254, in query
    _mysql.connection.query(self, query)
django.db.utils.OperationalError: (1054, "Unknown column 'product.image_id_id' in 'field list'")
2023-07-04 17:35:23,758 - INFO - Starts
2023-07-04 17:35:23,758 - INFO - Serialized
